<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Media</name>
   <tag></tag>
   <elementGuidId>e884548a-a1fb-48d7-a5b4-c359445ff44c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div/div[2]/div/div[2]/div/div/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c45036ae-52fd-4f31-be7c-813b1d6670e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Media</value>
      <webElementGuid>7855cc3b-6efe-4cba-9549-6eceeaaba291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://video.tuoitre.vn</value>
      <webElementGuid>8e0a58c9-2f06-401b-bc03-fd4d8dd765fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>4b3ac719-093d-47ef-bf3b-8dc0639a4bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Media
                                    </value>
      <webElementGuid>9f7d0df3-126f-46cd-a7d5-66dd91254712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;wapper&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header__sc&quot;]/div[@class=&quot;header__middle&quot;]/div[@class=&quot;header__postion&quot;]/div[@class=&quot;header__nav&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header__nav-flex&quot;]/ul[@class=&quot;menu-nav&quot;]/li[2]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>6350b237-d78d-4f44-91d9-bd24a4fd920a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div[2]/div/div[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>76210aeb-8812-4832-97af-bbe7f778f092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Media')]</value>
      <webElementGuid>fe8dd2fa-cc87-4d11-9b3b-41e52457c1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký Tuổi Trẻ Sao'])[1]/following::a[4]</value>
      <webElementGuid>a1eec9be-3dbe-4bc2-b65a-d754518b8d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt báo'])[1]/following::a[5]</value>
      <webElementGuid>6124b4e8-36ac-420f-b5fa-4e7e6797c39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời sự'])[1]/preceding::a[1]</value>
      <webElementGuid>eaca60e3-2f4a-4805-ad50-8d68843ee501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thế giới'])[1]/preceding::a[2]</value>
      <webElementGuid>23ecd8f1-7040-4671-b1ed-842e856d0c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Media']/parent::*</value>
      <webElementGuid>105955f1-11f3-4015-82e2-a77511a09ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://video.tuoitre.vn')]</value>
      <webElementGuid>31c846a1-f83b-48ed-a015-aa46d066aa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>143950fc-1a4f-443f-a1e1-da32486a9375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Media' and @href = 'https://video.tuoitre.vn' and (text() = 'Media
                                    ' or . = 'Media
                                    ')]</value>
      <webElementGuid>4191f6fa-7947-456f-93b6-bef17e94e7c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
